name: Build

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          path: src

      - name: Checkout builds branch
        uses: actions/checkout@v3
        with:
          ref: builds
          path: builds

      - name: Clean old builds
        run: |
          rm -f builds/*.apk || true
          rm -f builds/*.cs3 || true

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build APK
        run: |
          cd src
          chmod +x gradlew
          ./gradlew assembleDebug
          cp app/build/outputs/apk/debug/app-debug.apk ../builds/my-webview.apk

      - name: Commit and push build output
        run: |
          cd builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit --amend -m "Build $GITHUB_SHA" || echo "No changes to commit"
          git push --force
